08-01-2025 at 11:32:38 | DEBUG | RESPONSE:{'status_code': 422, 'status': False, 'message': "'EmpSchemaIn' object has no attribute 'status'"}
08-01-2025 at 11:38:14 | DEBUG | RESPONSE:{'status_code': 422, 'status': False, 'message': "Type:<class 'AttributeError'>'EmpSchemaIn' object has no attribute 'status'"}
08-01-2025 at 11:52:07 | DEBUG | RESPONSE:{'status_code': 422, 'status': False, 'message': "Type:<class 'pydantic_core._pydantic_core.ValidationError'>, Message:3 validation errors for EmpSchemaOut\nemp_name\n  Field required [type=missing, input_value={'status_code': 200, 'sta...app.com', 'status': 1}]}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.10/v/missing\nemail\n  Field required [type=missing, input_value={'status_code': 200, 'sta...app.com', 'status': 1}]}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.10/v/missing\nmobile\n  Field required [type=missing, input_value={'status_code': 200, 'sta...app.com', 'status': 1}]}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.10/v/missing"}
08-01-2025 at 12:12:08 | DEBUG | RESPONSE:{'status_code': 422, 'status': False, 'message': "Type:<class 'pydantic_core._pydantic_core.ValidationError'>, Message:1 validation error for EmpSchemaOut\ndata.0.mobile\n  Field required [type=missing, input_value={'id': 2, 'emp_name': 'At...ysapp.com', 'status': 1}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.10/v/missing"}
