09-01-2025 at 10:25:55 | DEBUG | RESPONSE:{'status_code': 422, 'status': False, 'message': "Type:<class 'pydantic_core._pydantic_core.ValidationError'>, Message:1 validation error for EmpSchemaOut\ndata.0.mobile\n  Field required [type=missing, input_value={'id': 3, 'emp_name': 'At...ysapp.com', 'status': 1}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.10/v/missing"}
09-01-2025 at 10:28:17 | DEBUG | RESPONSE:{'status_code': 200, 'status': True, 'message': 'Emp m successfully created', 'data': [{'id': 4, 'emp_name': 'Atul', 'email': 'atul@comsysapp.com', 'mobile': '000000', 'status': 1}]}
09-01-2025 at 10:50:33 | DEBUG | RESPONSE:{'status_code': 200, 'status': True, 'message': 'Emp m successfully created', 'data': [{'id': 5, 'emp_name': 'Atul', 'email': 'atul@comsysapp.com', 'mobile': '000000', 'status': 1}]}
09-01-2025 at 11:08:51 | DEBUG | RESPONSE:{'status_code': 200, 'status': True, 'message': 'Emp m successfully created', 'data': [{'id': 1, 'emp_name': 'Atul', 'email': 'atul@abc.abc', 'mobile': '123456789', 'status': 1}]}
09-01-2025 at 11:19:42 | DEBUG | RESPONSE:{'status_code': 200, 'status': True, 'message': 'Emp m successfully created', 'data': [{'id': 2, 'emp_name': 'Atul', 'email': 'atul@abc.abc', 'mobile': '123456789', 'status': 1}]}
09-01-2025 at 11:25:31 | DEBUG | RESPONSE:{'status_code': 200, 'status': True, 'message': 'Emp m successfully created', 'data': [{'id': 1, 'emp_name': 'Atul', 'email': 'atul@abc.abc', 'mobile': '123456789', 'status': 1}]}
09-01-2025 at 11:25:38 | DEBUG | RESPONSE:{'status_code': 422, 'status': False, 'message': 'Type:<class \'sqlalchemy.exc.IntegrityError\'>, Message:(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ix_emp_m_email"\nDETAIL:  Key (email)=(atul@abc.abc) already exists.\n\n[SQL: INSERT INTO emp_m (emp_name, email, mobile, status, password, remember_token, updated_at, deleted_at) VALUES (%(emp_name)s, %(email)s, %(mobile)s, %(status)s, %(password)s, %(remember_token)s, %(updated_at)s, %(deleted_at)s) RETURNING emp_m.id, emp_m.created_at]\n[parameters: {\'emp_name\': \'Atul\', \'email\': \'atul@abc.abc\', \'mobile\': \'123456789\', \'status\': 1, \'password\': \'$2b$12$DbeSkUIVZEeQxTzSogEsqOFGEp0P1FzMJkcr.3hhUGepNCWT5RgMa\', \'remember_token\': None, \'updated_at\': None, \'deleted_at\': None}]\n(Background on this error at: https://sqlalche.me/e/20/gkpj)'}
